name: CI

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build_validate_test:
    uses: openmcp-project/build/.github/workflows/ci.lib.yaml@e6fddacd119db2136c40f9d5cca6a9ce3920b435 # main
    secrets: inherit
