name: CI

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build_validate_test:
    uses: openmcp-project/build/.github/workflows/ci.lib.yaml@6e6df00f34641997459388343b33f4bb1cc964c6 # main
    secrets: inherit
