name: Publish

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  packages: write

jobs:
  release_publish:
    uses: openmcp-project/build/.github/workflows/publish.lib.yaml@6e6df00f34641997459388343b33f4bb1cc964c6 # main
    secrets: inherit
