name: Versioned Release

on:
  push:
    branches:
      - main

permissions:
  contents: write # we need this to be able to push tags
  pull-requests: read

jobs:
  release_tag:
    uses: openmcp-project/build/.github/workflows/release.lib.yaml@e6fddacd119db2136c40f9d5cca6a9ce3920b435 # main
    secrets: inherit
