name: Renovate Generate

on:
  push:
    branches:
      - "renovate/**"

permissions:
  contents: write

jobs:
  generate:
    uses: openmcp-project/build/.github/workflows/renovate-generate.lib.yaml@37c2f74d0dbeb6be81024420734dcec9790e9a5c # main
    secrets: inherit
