name: Renovate Generate

on:
  push:
    branches:
      - "renovate/**"

permissions:
  contents: write

jobs:
  generate:
    uses: openmcp-project/build/.github/workflows/renovate-generate.lib.yaml@58c5ff00ec953dd6b5908f6658f1d1b522c06431 # main
    secrets: inherit
