name: REUSE Compliance Check

on: [push, pull_request]

permissions:
  contents: read

jobs:
  run_reuse:
    uses: openmcp-project/build/.github/workflows/reuse.lib.yaml@6e6df00f34641997459388343b33f4bb1cc964c6 # main
    secrets: inherit
